### ISSUE TITLE
CI Infra: Properly setup the Database without re-running ingestion all the time

### ISSUE THREAD

**Issue by fwilhe** [gardenlinux/glvd#102]
Currently there are 2 ways how glvd can be setup in the CI infra

- Use the container image without any data/schema und run the ingestion process (this takes a long time and may fail depending on the cluster location)
- Use the container image with a data snapshot (this is obviously not a way to run it in production)

We should look into proper backup/restore concepts for databases, for example [with this helm chart](https://artifacthub.io/packages/helm/bitnami/postgresql#backup-and-restore-postgresql-deployments)

**Comment by pnpavlov** [comment]
I would recommend that in the context of this task and covering our development needs (no production usage):
1. Adopt a helm chart based on the standard ones available online without HA (e.g. Bitnami prepped [this one](https://github.com/bitnami/charts/tree/main/bitnami/postgresql)).
2. Deploy clean DB instance in our development cluster that is available only within the context of the namespace and not exposed to the public internet in any way.
3. Setup the cron job and let it run first time for a full data load (long).
4. Take a database SQL backup for local needs and document how the database dump could be downloaded and re-imported in local database.
5. Let the cron job continue to run daily for delta loads (short).
6. Occasionally (e.g. monthly?) update the database dump file backup for local development work.
