### ISSUE TITLE
Optimise the image content 

### ISSUE THREAD

**Issue by pnpavlov** [gardenlinux/glvd#129]
As engineer maintaining the vulnerability database backend, I would like to have a minimal image that is optimized and has limited size and only relevant content.

- [ ] Optimise the Java runtime for the app by applying the concept of a separated build container in multi stage container build
- [ ] Optmise the Java runtime environment included in the final image via jlink. Example [here](https://learn.microsoft.com/en-us/java/openjdk/java-jlink-runtimes)  https://github.com/gardenlinux/glvd-api/pull/53
- [x] Optimize the container image via [unbase_oci](https://github.com/gardenlinux/unbase_oci) tooling. #128

**Comment by fwilhe** [comment]
Stats on space savings

```
full image (gardenlinux base, sapmachine 21 jre headless, glvd.jar) : 319 MB
bare image (sapmachine 21 jre headless, glvd.jar)                   : 235 MB
jlink+bare image (stripped down jre, glvd.jar)                      : 156 MB
```
