### ISSUE TITLE
Review & finalize initial API design specification and tooling

### ISSUE THREAD

**Issue by pnpavlov** [gardenlinux/glvd#80]
Perform next iteration on the API specification and finalize the first version that satisfies the pilot use-case/epic.
The API should be:
- REST based following best practices
- Documented in easy to use for developers way
- Versioned
- Organized in a way that enables expansion.

**Comment by pnpavlov** [comment]
@gehoern will review the content the api returns

**Comment by fwilhe** [comment]
seems not relevant anymore
