### ISSUE TITLE
Maintain a list of impacted package(s) by a CVE

### ISSUE THREAD

**Issue by pnpavlov** [gardenlinux/glvd#88]

**Comment by fwilhe** [comment]
given a gardenlinux version and a cve you will get the packages affected by this cve. I think this is what was meant with this issue @pnpavlov 

Searched for an example where one cve affects more than one package and this is what I came up with:

<img width="845" alt="Screenshot 2024-09-06 at 11 08 32" src="https://github.com/user-attachments/assets/6f7ff788-e206-4257-9e90-0ffd891be480">

**Comment by fwilhe** [comment]
Implemented with this endpoint https://gardenlinux.github.io/glvd-api/#_get_packages_by_vulnerabilities
