### ISSUE TITLE
Evaluate Spring Data REST for implementation

### ISSUE THREAD

**Issue by fwilhe** [gardenlinux/glvd#96]
[Spring Data REST](https://docs.spring.io/spring-data/rest/reference/index.html) might be useful to address #95 , #94 without the need to write lots of custom code for pagination and sorting.

Spring Data REST generates API endpoints automatically with consistent sorting and pagination by default.

Spring Data REST generates a Hypermedia REST API which is not what we want or need for GLVD, we rather want 'JSON over HTTP' which [can't be meaningfully built with Spring Data REST](https://stackoverflow.com/a/24451993).

Without Spring Data REST [pagination and sorting has to be implemented manually](https://www.baeldung.com/spring-data-jpa-pagination-sorting).

Result of the evaluation:
Don't use Spring Data REST for glvd.

**Comment by pnpavlov** [comment]
thank you for the detailed research and thinking it through!

✅ Don't use Spring Data REST for glvd.
